USE SalesAnalytics;

UPDATE SuperstoreSales
SET State = UPPER(LTRIM(RTRIM(State)));

SELECT DISTINCT State from SuperstoreSales

UPDATE SuperstoreSales
SET State = CASE
    WHEN State IN ('NY', 'New York', 'new york') THEN 'NEW YORK'
    WHEN State IN ('Californi', 'CA', 'California') THEN 'CALIFORNIA'
    WHEN State IN ('Tex', 'TX', 'texas') THEN 'TEXAS'
    WHEN State IN ('Fl', 'FL', 'florida') THEN 'FLORIDA'
    WHEN State IN ('IL', 'Il', 'illinois') THEN 'ILLINOIS'
    -- Add other corrections as needed
    ELSE State
END;

SELECT DISTINCT State
FROM SuperstoreSales
WHERE State NOT IN (
    'ALABAMA','ALASKA','ARIZONA','ARKANSAS','CALIFORNIA','COLORADO', 
    'CONNECTICUT','DELAWARE','FLORIDA','GEORGIA','HAWAII','IDAHO',
    'ILLINOIS','INDIANA','IOWA','KANSAS','KENTUCKY','LOUISIANA',
    'MAINE','MARYLAND','MASSACHUSETTS','MICHIGAN','MINNESOTA',
    'MISSISSIPPI','MISSOURI','MONTANA','NEBRASKA','NEVADA','NEW HAMPSHIRE',
    'NEW JERSEY','NEW MEXICO','NEW YORK','NORTH CAROLINA','NORTH DAKOTA',
    'OHIO','OKLAHOMA','OREGON','PENNSYLVANIA','RHODE ISLAND','SOUTH CAROLINA',
    'SOUTH DAKOTA','TENNESSEE','TEXAS','UTAH','VERMONT','VIRGINIA','WASHINGTON',
    'WEST VIRGINIA','WISCONSIN','WYOMING','DISTRICT OF COLUMBIA'
);