USE SalesAnalytics;

UPDATE SuperstoreSales
SET Sub_Category = UPPER(LTRIM(RTRIM(Sub_Category)));

UPDATE SuperstoreSales
SET Sub_Category = CASE
    -- FURNITURE
    WHEN Sub_Category IN ('CHAIRS', 'CHAIR') THEN 'CHAIRS'
    WHEN Sub_Category IN ('BOOK CASES', 'BOOKCASES') THEN 'BOOKCASES'
    WHEN Sub_Category IN ('TABLE', 'TABLES') THEN 'TABLES'
    WHEN Sub_Category IN ('STORAGE', 'STORAGES') THEN 'STORAGE'
    WHEN Sub_Category IN ('FURNISHING', 'FURNISHINGS') THEN 'FURNISHINGS'
    
    -- OFFICE SUPPLIES
    WHEN Sub_Category IN ('APPLIANCE', 'APPLIANCES') THEN 'APPLIANCES'
    WHEN Sub_Category IN ('BINDER', 'BINDERS') THEN 'BINDERS'
    WHEN Sub_Category IN ('ENVELOPE', 'ENVELOPES') THEN 'ENVELOPES'
    WHEN Sub_Category IN ('ARTS', 'ART') THEN 'ART'
    WHEN Sub_Category IN ('FASTENER', 'FASTENERS') THEN 'FASTENERS'
    WHEN Sub_Category IN ('LABEL', 'LABELS') THEN 'LABELS'
    WHEN Sub_Category IN ('PAPER', 'PAPERS') THEN 'PAPER'
    WHEN Sub_Category IN ('PHONE', 'PHONES') THEN 'PHONES'
    WHEN Sub_Category IN ('RUBBER BAND', 'RUBBER BANDS') THEN 'RUBBER BANDS'
    WHEN Sub_Category IN ('SCISSORS', 'SCISSOR') THEN 'SCISSORS'
    
    -- TECHNOLOGY
    WHEN Sub_Category IN ('ACCESSORY', 'ACCESSORIES') THEN 'ACCESSORIES'
    WHEN Sub_Category IN ('COPIER', 'COPIERS') THEN 'COPIERS'
    WHEN Sub_Category IN ('MACHINE', 'MACHINES') THEN 'MACHINES'
    WHEN Sub_Category IN ('PHONE', 'PHONES') THEN 'PHONES'
    WHEN Sub_Category IN ('TABLET', 'TABLETS') THEN 'TABLETS'
    
    ELSE Sub_Category
END;


SELECT *
FROM SuperstoreSales
WHERE Sub_Category IS NULL
   OR LTRIM(RTRIM(Sub_Category)) = '';

SELECT *
FROM SuperstoreSales
WHERE (Category = 'FURNITURE' AND Sub_Category NOT IN ('BOOKCASES','CHAIRS','FURNISHINGS','STORAGE','TABLES'))
   OR (Category = 'OFFICE SUPPLIES' AND Sub_Category NOT IN ('APPLIANCES','ART','BINDERS','ENVELOPES','FASTENERS','LABELS','PAPER','PHONES','RUBBER BANDS','SCISSORS','STORAGE', 'SUPPLIES'))
   OR (Category = 'TECHNOLOGY' AND Sub_Category NOT IN ('ACCESSORIES','COPIERS','MACHINES','PHONES','TABLETS'));



